version: 2
jobs:
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: echo "Success"
  e2e_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: sleep 100
      - run: echo "Fail"
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - e2e_test:
          requires:
            - test
          filters:
            branches:
              only: master
