version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: echo "Success"
  e2e_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: echo "Fail"
      - run: exit 1
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - hold:
          type: approval
          requires: [test]
      - e2e_test:
          requires:
            - hold
          filters:
            branches:
              only: master
